# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoVentaCamisa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogoVentaCamisa(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 523)
        self.lbl_seleccion_talla = QtWidgets.QLabel(Dialog)
        self.lbl_seleccion_talla.setGeometry(QtCore.QRect(40, 40, 200, 17))
        self.lbl_seleccion_talla.setObjectName("lbl_seleccion_talla")
        self.lbl_seleccion_pago = QtWidgets.QLabel(Dialog)
        self.lbl_seleccion_pago.setGeometry(QtCore.QRect(40, 270, 200, 17))
        self.lbl_seleccion_pago.setObjectName("lbl_seleccion_pago")
        self.lbl_mostrar_talla_pago = QtWidgets.QLabel(Dialog)
        self.lbl_mostrar_talla_pago.setGeometry(QtCore.QRect(40, 460, 391, 41))
        self.lbl_mostrar_talla_pago.setText("")
        self.lbl_mostrar_talla_pago.setObjectName("lbl_mostrar_talla_pago")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 70, 241, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vly_talla_camisa = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vly_talla_camisa.setContentsMargins(0, 0, 0, 0)
        self.vly_talla_camisa.setObjectName("vly_talla_camisa")
        self.rbn_talla_l = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbn_talla_l.setObjectName("rbn_talla_l")
        self.vly_talla_camisa.addWidget(self.rbn_talla_l)
        self.rbn_talla_xxl = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbn_talla_xxl.setObjectName("rbn_talla_xxl")
        self.vly_talla_camisa.addWidget(self.rbn_talla_xxl)
        self.rbn_talla_xl = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbn_talla_xl.setObjectName("rbn_talla_xl")
        self.vly_talla_camisa.addWidget(self.rbn_talla_xl)
        self.rbn_talla_m = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbn_talla_m.setObjectName("rbn_talla_m")
        self.vly_talla_camisa.addWidget(self.rbn_talla_m)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 300, 241, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vly_metodo_pago = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vly_metodo_pago.setContentsMargins(0, 0, 0, 0)
        self.vly_metodo_pago.setObjectName("vly_metodo_pago")
        self.rbn_pago_tarjeta = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbn_pago_tarjeta.setObjectName("rbn_pago_tarjeta")
        self.vly_metodo_pago.addWidget(self.rbn_pago_tarjeta)
        self.rbn_pago_domiciliado = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbn_pago_domiciliado.setObjectName("rbn_pago_domiciliado")
        self.vly_metodo_pago.addWidget(self.rbn_pago_domiciliado)
        self.rbn_pago_presencial = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbn_pago_presencial.setObjectName("rbn_pago_presencial")
        self.vly_metodo_pago.addWidget(self.rbn_pago_presencial)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Venta"))
        self.lbl_seleccion_talla.setText(_translate("Dialog", "TALLA:"))
        self.lbl_seleccion_pago.setText(_translate("Dialog", "PAGO:"))
        self.rbn_talla_l.setText(_translate("Dialog", "L"))
        self.rbn_talla_xxl.setText(_translate("Dialog", "XXL"))
        self.rbn_talla_xl.setText(_translate("Dialog", "XL"))
        self.rbn_talla_m.setText(_translate("Dialog", "M"))
        self.rbn_pago_tarjeta.setText(_translate("Dialog", "Tarjeta Crédito / Débito"))
        self.rbn_pago_domiciliado.setText(_translate("Dialog", "Domiciliado"))
        self.rbn_pago_presencial.setText(_translate("Dialog", "Contrareembolso"))
