# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoPizza.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogoPizza(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 394)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 461, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vly_precio_opciones = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vly_precio_opciones.setContentsMargins(0, 0, 0, 0)
        self.vly_precio_opciones.setObjectName("vly_precio_opciones")
        self.lbl_precio_basico = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.lbl_precio_basico.setFont(font)
        self.lbl_precio_basico.setObjectName("lbl_precio_basico")
        self.vly_precio_opciones.addWidget(self.lbl_precio_basico)
        self.lbl_seleccion_ingredientes = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_seleccion_ingredientes.setObjectName("lbl_seleccion_ingredientes")
        self.vly_precio_opciones.addWidget(self.lbl_seleccion_ingredientes)
        self.chk_queso = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chk_queso.setObjectName("chk_queso")
        self.vly_precio_opciones.addWidget(self.chk_queso)
        self.chk_champ = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chk_champ.setObjectName("chk_champ")
        self.vly_precio_opciones.addWidget(self.chk_champ)
        self.chk_salsa = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chk_salsa.setObjectName("chk_salsa")
        self.vly_precio_opciones.addWidget(self.chk_salsa)
        self.lbl_precio_final = QtWidgets.QLabel(Dialog)
        self.lbl_precio_final.setGeometry(QtCore.QRect(50, 270, 401, 91))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.lbl_precio_final.setFont(font)
        self.lbl_precio_final.setText("")
        self.lbl_precio_final.setObjectName("lbl_precio_final")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pizza y precio"))
        self.lbl_precio_basico.setText(_translate("Dialog", "PRECIO DE PIZZA: 15€"))
        self.lbl_seleccion_ingredientes.setText(_translate("Dialog", "Seleccione los ingredientes:"))
        self.chk_queso.setText(_translate("Dialog", "Queso"))
        self.chk_champ.setText(_translate("Dialog", "Champiñones"))
        self.chk_salsa.setText(_translate("Dialog", "Salsa"))
