# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoHelados.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogoHelados(object):
    def setupUi(self, Heladeria):
        Heladeria.setObjectName("Heladeria")
        Heladeria.resize(543, 423)
        self.lbl_menu = QtWidgets.QLabel(Heladeria)
        self.lbl_menu.setGeometry(QtCore.QRect(30, 20, 67, 17))
        self.lbl_menu.setObjectName("lbl_menu")
        self.lbl_seleccione_helado = QtWidgets.QLabel(Heladeria)
        self.lbl_seleccione_helado.setGeometry(QtCore.QRect(30, 100, 151, 17))
        self.lbl_seleccione_helado.setObjectName("lbl_seleccione_helado")
        self.lbl_seleccione_bebida = QtWidgets.QLabel(Heladeria)
        self.lbl_seleccione_bebida.setGeometry(QtCore.QRect(270, 100, 191, 20))
        self.lbl_seleccione_bebida.setObjectName("lbl_seleccione_bebida")
        self.gbx_helados = QtWidgets.QGroupBox(Heladeria)
        self.gbx_helados.setGeometry(QtCore.QRect(30, 130, 211, 171))
        self.gbx_helados.setCheckable(True)
        self.gbx_helados.setObjectName("gbx_helados")
        self.chk_chocolate = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_chocolate.setGeometry(QtCore.QRect(20, 40, 171, 23))
        self.chk_chocolate.setObjectName("chk_chocolate")
        self.chk_vainilla = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_vainilla.setGeometry(QtCore.QRect(20, 70, 171, 23))
        self.chk_vainilla.setObjectName("chk_vainilla")
        self.chk_fresa = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_fresa.setGeometry(QtCore.QRect(20, 100, 171, 23))
        self.chk_fresa.setObjectName("chk_fresa")
        self.chk_limon = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_limon.setGeometry(QtCore.QRect(20, 130, 161, 23))
        self.chk_limon.setObjectName("chk_limon")
        self.gbx_bebidas = QtWidgets.QGroupBox(Heladeria)
        self.gbx_bebidas.setGeometry(QtCore.QRect(270, 130, 201, 171))
        self.gbx_bebidas.setCheckable(True)
        self.gbx_bebidas.setObjectName("gbx_bebidas")
        self.chk_agua = QtWidgets.QCheckBox(self.gbx_bebidas)
        self.chk_agua.setGeometry(QtCore.QRect(20, 40, 92, 23))
        self.chk_agua.setObjectName("chk_agua")
        self.chk_cafe = QtWidgets.QCheckBox(self.gbx_bebidas)
        self.chk_cafe.setGeometry(QtCore.QRect(20, 80, 92, 23))
        self.chk_cafe.setObjectName("chk_cafe")
        self.chk_refresco = QtWidgets.QCheckBox(self.gbx_bebidas)
        self.chk_refresco.setGeometry(QtCore.QRect(20, 120, 92, 23))
        self.chk_refresco.setObjectName("chk_refresco")
        self.lbl_total = QtWidgets.QLabel(Heladeria)
        self.lbl_total.setGeometry(QtCore.QRect(40, 320, 421, 71))
        self.lbl_total.setText("")
        self.lbl_total.setObjectName("lbl_total")

        self.retranslateUi(Heladeria)
        QtCore.QMetaObject.connectSlotsByName(Heladeria)

    def retranslateUi(self, Heladeria):
        _translate = QtCore.QCoreApplication.translate
        Heladeria.setWindowTitle(_translate("Heladeria", "Heladería Dialog"))
        self.lbl_menu.setText(_translate("Heladeria", "Menú"))
        self.lbl_seleccione_helado.setText(_translate("Heladeria", "Seleccione helado"))
        self.lbl_seleccione_bebida.setText(_translate("Heladeria", "Selecione bebida"))
        self.gbx_helados.setTitle(_translate("Heladeria", "Helados"))
        self.chk_chocolate.setText(_translate("Heladeria", "Chocolate 5€"))
        self.chk_vainilla.setText(_translate("Heladeria", "Vainilla 4€"))
        self.chk_fresa.setText(_translate("Heladeria", "Fresa 6€"))
        self.chk_limon.setText(_translate("Heladeria", "Limón 3€"))
        self.gbx_bebidas.setTitle(_translate("Heladeria", "Bebidas"))
        self.chk_agua.setText(_translate("Heladeria", "Agua 2€"))
        self.chk_cafe.setText(_translate("Heladeria", "Cafe 3€"))
        self.chk_refresco.setText(_translate("Heladeria", "Refresco 4€"))
