# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoClaseVuelo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogoClaseVuelo(object):
    def setupUi(self, DialogoClaseVuelo):
        DialogoClaseVuelo.setObjectName("DialogoClaseVuelo")
        DialogoClaseVuelo.resize(379, 280)
        self.lbl_escoja_clase_vuelo = QtWidgets.QLabel(DialogoClaseVuelo)
        self.lbl_escoja_clase_vuelo.setGeometry(QtCore.QRect(40, 30, 251, 17))
        self.lbl_escoja_clase_vuelo.setObjectName("lbl_escoja_clase_vuelo")
        self.rbn_primera_clase = QtWidgets.QRadioButton(DialogoClaseVuelo)
        self.rbn_primera_clase.setGeometry(QtCore.QRect(50, 80, 160, 23))
        self.rbn_primera_clase.setObjectName("rbn_primera_clase")
        self.rbn_clase_negocios = QtWidgets.QRadioButton(DialogoClaseVuelo)
        self.rbn_clase_negocios.setGeometry(QtCore.QRect(50, 130, 160, 23))
        self.rbn_clase_negocios.setObjectName("rbn_clase_negocios")
        self.rbn_clase_economica = QtWidgets.QRadioButton(DialogoClaseVuelo)
        self.rbn_clase_economica.setGeometry(QtCore.QRect(50, 180, 160, 23))
        self.rbn_clase_economica.setObjectName("rbn_clase_economica")
        self.lbl_resultado_seleccion = QtWidgets.QLabel(DialogoClaseVuelo)
        self.lbl_resultado_seleccion.setGeometry(QtCore.QRect(60, 240, 241, 17))
        self.lbl_resultado_seleccion.setText("")
        self.lbl_resultado_seleccion.setObjectName("lbl_resultado_seleccion")

        self.retranslateUi(DialogoClaseVuelo)
        QtCore.QMetaObject.connectSlotsByName(DialogoClaseVuelo)

    def retranslateUi(self, DialogoClaseVuelo):
        _translate = QtCore.QCoreApplication.translate
        DialogoClaseVuelo.setWindowTitle(_translate("DialogoClaseVuelo", "Clase Vuelo"))
        self.lbl_escoja_clase_vuelo.setText(_translate("DialogoClaseVuelo", "Escoja la clase del vuelo:"))
        self.rbn_primera_clase.setText(_translate("DialogoClaseVuelo", "Primera clase"))
        self.rbn_clase_negocios.setText(_translate("DialogoClaseVuelo", "Clase negocios"))
        self.rbn_clase_economica.setText(_translate("DialogoClaseVuelo", "Clase económica"))
