# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoSaludo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoSaludar(object):
    def setupUi(self, DialogoSaludar):
        DialogoSaludar.setObjectName("DialogoSaludar")
        DialogoSaludar.resize(320, 182)
        self.lbl_escriba_nombre = QtWidgets.QLabel(DialogoSaludar)
        self.lbl_escriba_nombre.setGeometry(QtCore.QRect(10, 40, 141, 17))
        self.lbl_escriba_nombre.setObjectName("lbl_escriba_nombre")
        self.txt_nombre = QtWidgets.QLineEdit(DialogoSaludar)
        self.txt_nombre.setGeometry(QtCore.QRect(160, 40, 141, 25))
        self.txt_nombre.setObjectName("txt_nombre")
        self.lbl_saludo = QtWidgets.QLabel(DialogoSaludar)
        self.lbl_saludo.setGeometry(QtCore.QRect(10, 80, 141, 17))
        self.lbl_saludo.setObjectName("lbl_saludo")
        self.lbl_msg_saludo = QtWidgets.QLabel(DialogoSaludar)
        self.lbl_msg_saludo.setGeometry(QtCore.QRect(160, 80, 141, 17))
        self.lbl_msg_saludo.setText("")
        self.lbl_msg_saludo.setObjectName("lbl_msg_saludo")
        self.btn_saludar = QtWidgets.QPushButton(DialogoSaludar)
        self.btn_saludar.setGeometry(QtCore.QRect(160, 120, 141, 25))
        self.btn_saludar.setObjectName("btn_saludar")

        self.retranslateUi(DialogoSaludar)
        QtCore.QMetaObject.connectSlotsByName(DialogoSaludar)

    def retranslateUi(self, DialogoSaludar):
        _translate = QtCore.QCoreApplication.translate
        DialogoSaludar.setWindowTitle(_translate("DialogoSaludar", "Saludo"))
        self.lbl_escriba_nombre.setText(_translate("DialogoSaludar", "Escriba su nombre:"))
        self.lbl_saludo.setText(_translate("DialogoSaludar", "Saludo"))
        self.btn_saludar.setText(_translate("DialogoSaludar", "Saludar"))
